baseURL = 'https://abbeyhultonunitedfootball.club/'
languageCode = 'en-gb'
title = 'Abbey Hulton United Football Club'
theme = 'ananke'

[params]
    site_logo = "images/logo_trans_s.png"
    text_color = "bg-white"
    background_color_class = "bg-orange"
    favicon = "favicon.ico"
    custom_css = ["css/custom.css"]
    body_classes = "sans-serif bg-white"


[[params.ananke_socials]]
    name = "twitter"
    url = "https://www.twitter.com/HultonUtd"
    label = "Twitter"

[[params.ananke_socials]]
    name = "facebook"
    url = "https://www.facebook.com/abbeyhultonutd"
    label = "Facebook"

[[menu.main]]
    name       = "Home"
    identifier = "home"
    url        = "/"
    weight     = 1
